// <auto-generated />
using System;
using BildirimTestApp.Server.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BildirimTestApp.Server.Migrations
{
    [DbContext(typeof(TestDbContext))]
    [Migration("20240719074819_mig_02")]
    partial class mig_02
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BildirimTestApp.Server.Models.Gorev", b =>
                {
                    b.Property<int>("GorevId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GorevId"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("GorevSonTarih")
                        .HasColumnType("datetime2");

                    b.HasKey("GorevId");

                    b.ToTable("Gorevs");
                });

            modelBuilder.Entity("BildirimTestApp.Server.Models.SisBildirim", b =>
                {
                    b.Property<int>("BildirimId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BildirimId"));

                    b.Property<int>("BildirimIcerikId")
                        .HasColumnType("int");

                    b.Property<int>("GonderilecekKullaniciId")
                        .HasColumnType("int");

                    b.Property<int>("GonderimDurumu")
                        .HasColumnType("int");

                    b.Property<bool>("GorulduDurumu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("(CONVERT([bit],(0)))");

                    b.HasKey("BildirimId");

                    b.HasIndex(new[] { "BildirimIcerikId" }, "IX_SisBildirim_BildirimIcerikId");

                    b.HasIndex(new[] { "GonderilecekKullaniciId" }, "IX_SisBildirim_GonderilecekKullaniciId");

                    b.ToTable("SisBildirim", (string)null);
                });

            modelBuilder.Entity("BildirimTestApp.Server.Models.SisBildirimIcerik", b =>
                {
                    b.Property<int>("BildirimIcerikId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BildirimIcerikId"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(1000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Json")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<DateTime>("OlusturulanTarih")
                        .HasColumnType("datetime");

                    b.HasKey("BildirimIcerikId");

                    b.ToTable("SisBildirimIcerik", (string)null);
                });

            modelBuilder.Entity("BildirimTestApp.Server.Models.SisBildirimOutbox", b =>
                {
                    b.Property<int>("BildirimOutboxId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BildirimOutboxId"));

                    b.Property<int>("BildirimId")
                        .HasColumnType("int");

                    b.Property<int>("GonderimDenemeSayisi")
                        .HasColumnType("int");

                    b.HasKey("BildirimOutboxId");

                    b.HasIndex(new[] { "BildirimId" }, "IX_SisBildirimOutbox_BildirimId");

                    b.ToTable("SisBildirimOutbox", (string)null);
                });

            modelBuilder.Entity("BildirimTestApp.Server.Models.SisKullanici", b =>
                {
                    b.Property<int>("KullaniciId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KullaniciId"));

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("KullaniciSifresi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rol")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.HasKey("KullaniciId");

                    b.HasIndex(new[] { "KullaniciAdi" }, "UK_SisKullanici")
                        .IsUnique();

                    b.ToTable("SisKullanici", (string)null);
                });

            modelBuilder.Entity("SisKullaniciGorev", b =>
                {
                    b.Property<int>("GorevsGorevId")
                        .HasColumnType("int");

                    b.Property<int>("SisKullanicisKullaniciId")
                        .HasColumnType("int");

                    b.HasKey("GorevsGorevId", "SisKullanicisKullaniciId");

                    b.HasIndex(new[] { "SisKullanicisKullaniciId" }, "IX_SisKullaniciGorevs_SisKullanicisKullaniciId");

                    b.ToTable("SisKullaniciGorevs", (string)null);
                });

            modelBuilder.Entity("BildirimTestApp.Server.Models.SisBildirim", b =>
                {
                    b.HasOne("BildirimTestApp.Server.Models.SisBildirimIcerik", "BildirimIcerik")
                        .WithMany("SisBildirims")
                        .HasForeignKey("BildirimIcerikId")
                        .IsRequired()
                        .HasConstraintName("FK_SisBildirim_SisBildirimIcerik");

                    b.HasOne("BildirimTestApp.Server.Models.SisKullanici", "GonderilecekKullanici")
                        .WithMany("SisBildirims")
                        .HasForeignKey("GonderilecekKullaniciId")
                        .IsRequired()
                        .HasConstraintName("FK_SisBildirim_SisKullanici");

                    b.Navigation("BildirimIcerik");

                    b.Navigation("GonderilecekKullanici");
                });

            modelBuilder.Entity("BildirimTestApp.Server.Models.SisBildirimOutbox", b =>
                {
                    b.HasOne("BildirimTestApp.Server.Models.SisBildirim", "Bildirim")
                        .WithMany("SisBildirimOutboxes")
                        .HasForeignKey("BildirimId")
                        .IsRequired()
                        .HasConstraintName("FK_SisBildirimOutbox_SisBildirim");

                    b.Navigation("Bildirim");
                });

            modelBuilder.Entity("SisKullaniciGorev", b =>
                {
                    b.HasOne("BildirimTestApp.Server.Models.Gorev", null)
                        .WithMany()
                        .HasForeignKey("GorevsGorevId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BildirimTestApp.Server.Models.SisKullanici", null)
                        .WithMany()
                        .HasForeignKey("SisKullanicisKullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BildirimTestApp.Server.Models.SisBildirim", b =>
                {
                    b.Navigation("SisBildirimOutboxes");
                });

            modelBuilder.Entity("BildirimTestApp.Server.Models.SisBildirimIcerik", b =>
                {
                    b.Navigation("SisBildirims");
                });

            modelBuilder.Entity("BildirimTestApp.Server.Models.SisKullanici", b =>
                {
                    b.Navigation("SisBildirims");
                });
#pragma warning restore 612, 618
        }
    }
}
